-- @generated-file-note
-- 文件：smart-tools-backend/db/data_tools.sql
-- 用途：数据库结构/迁移/初始化脚本
-- 用途：用于初始化/迁移数据库结构与基础数据
-- 安全：不要在脚本中写入生产口令、密钥或真实个人数据
INSERT INTO sys_tool (slug, name, category, description, keywords, enabled, sort_order) VALUES
('base-converter', '整数基数转换器', '编码/转换', '在不同的基数 (十进制, 十六进制, 二进制, 八进制) 之间转换数字', 'base,radix,hex,binary,octal,decimal', 1, 0),
('base64', 'Base64 编解码', '编码/转换', 'Base64 字符串编码与解码（支持 UTF-8）', 'base64,encode,decode', 1, 0),
('base64-file', 'Base64 文件转换', '编码/转换', '将文件转换为 Base64 DataURI 字符串', 'base64,file,image,datauri', 1, 0),
('bcrypt-generator', 'Bcrypt 加密', '安全', '使用 Bcrypt 对文本字符串进行哈希和比较', 'bcrypt,hash,password,security', 1, 0),
('bip39-generator', 'BIP39 密码生成器', '安全', '生成 BIP39 助记词和种子', 'bip39,mnemonic,seed,crypto,wallet', 1, 0),
('case-converter', '大小写转换', '文本处理', '文本大小写、驼峰、下划线等命名风格转换', 'case,upper,lower,camel,snake', 1, 0),
('code-generator', 'Spring Boot 代码生成器', '开发', '快速生成 Spring Boot 项目结构与 CRUD 代码', 'java,spring boot,generator,scaffold', 1, 0),
('color-converter', 'Color 转换器', '设计工具', 'HEX, RGB, RGBA, HSL, HSLA 颜色格式互转', 'color,hex,rgb,hsl,converter', 1, 0),
('date-converter', '日期时间转换', '格式转换', '时间戳、日期字符串、ISO8601 格式互转', 'date,time,timestamp,iso,format', 1, 0),
('encrypt-decrypt', '加密/解密文本', '安全', '使用加密算法 (AES, DES, RC4) 加密和解密文本', 'encrypt,decrypt,aes,des,rc4,crypto', 1, 0),
('hash-text', 'Hash 文本', '加密/解密', '计算文本的 MD5, SHA1, SHA256, SHA512 哈希值', 'hash,md5,sha1,sha256,crypto', 1, 0),
('hmac-generator', 'Hmac 生成器', '安全', '计算基于哈希的消息身份验证代码 (HMAC)', 'hmac,hash,security,signature', 1, 0),
('json-to-toml', 'JSON 转 TOML', '编码/转换', 'JSON 转换为 TOML', 'json,toml,converter', 1, 0),
('json-to-yaml', 'JSON/YAML 转换', '格式转换', 'JSON 与 YAML 格式互转', 'json,yaml,converter,format', 1, 0),
('list-converter', 'List 转换器', '编码/转换', '处理列表数据：排序、去重、分割等', 'list,array,sort,filter,converter', 1, 0),
('password-strength', '密码强度分析仪', '安全', '估算密码的强度和破解时间', 'password,strength,security,zxcvbn', 1, 0),
('pdf-signature-checker', 'PDF 签名检查器', '文件', '验证 PDF 文件的数字签名', 'pdf,signature,verify,file', 1, 0),
('roman-numeral', '罗马数字转换器', '编码/转换', '数字与罗马数字相互转换', 'roman,numeral,number,converter', 1, 0),
('rsa-generator', 'RSA 密钥对生成器', '安全', '生成新的随机 RSA 私钥和公钥证书', 'rsa,keypair,crypto,pem,public,private', 1, 0),
('text-to-binary', '文本到 ASCII 二进制', '编码/转换', '文本与其 ASCII 二进制表示形式互转', 'binary,ascii,text,01', 1, 0),
('text-to-nato', '文本转北约字母表', '编码/转换', '将文本转换为北约拼音字母', 'nato,phonetic,alphabet,text', 1, 0),
('text-to-unicode', '文本转 Unicode', '编码/转换', '解析文本并将其转换为 Unicode', 'unicode,text,escape', 1, 0),
('token-generator', 'Token 生成器', '生成器', '生成随机字符串、密码或 API Token', 'token,password,random,string', 1, 0),
('toml-to-json', 'TOML 到 JSON', '编码/转换', 'TOML 转换为 JSON', 'toml,json,converter', 1, 0),
('toml-to-yaml', 'TOML 到 YAML', '编码/转换', 'TOML 转换为 YAML', 'toml,yaml,converter', 1, 0),
('ulid-generator', 'ULID 生成器', '编码/标识', '生成随机的通用唯一词典可排序标识符 (ULID)', 'ulid,uuid,random,id', 1, 0),
('uuid-generator', 'UUID 生成器', '编码/标识', '生成 UUIDv4（浏览器端 crypto.randomUUID）', 'uuid,uuidv4,random', 1, 0),
('yaml-to-toml', 'YAML 到 TOML', '编码/转换', 'YAML 转换为 TOML', 'yaml,toml,converter', 1, 0),
('pdf-to-word', 'PDF 转 Word', '文档处理', '将 PDF 转换为可编辑的 Word 文档', 'pdf,word,docx,convert', 1, 10),
('word-to-pdf', 'Word 转 PDF', '文档处理', '将 Word 文档转换为 PDF 文件', 'word,pdf,docx,convert', 1, 10),
('pdf-merge', 'PDF 合并', '文档处理', '合并多个 PDF 为单一文件', 'pdf,merge,combine', 1, 10),
('pdf-split', 'PDF 拆分', '文档处理', '按页拆分 PDF，快速输出单页文件', 'pdf,split,pages', 1, 10),
('pdf-compress', 'PDF 压缩', '文档处理', '压缩 PDF 体积，便于传输分享', 'pdf,compress,optimize', 1, 10),
('pdf-watermark', 'PDF 水印', '文档处理', '为 PDF 添加文字或图片水印', 'pdf,watermark', 1, 10),
('pdf-to-images', 'PDF 转图片', '文档处理', '将 PDF 页面转换为图片', 'pdf,image,png,jpg', 1, 10),
('images-to-pdf', '图片转 PDF', '文档处理', '将多张图片合成为 PDF', 'image,pdf,convert', 1, 10),
('pdf-ocr', 'PDF OCR 识别', '文档处理', '识别 PDF 扫描件中的文字内容', 'pdf,ocr,text', 1, 10),
('excel-to-pdf', 'Excel 转 PDF', '文档处理', '将 Excel 表格导出为 PDF', 'excel,pdf,xlsx', 1, 10),
('ppt-to-pdf', 'PPT 转 PDF', '文档处理', '将 PPT 演示文稿导出为 PDF', 'ppt,pdf,slides', 1, 10),
('image-compress', '图片压缩', '图片处理', '压缩图片体积，保持清晰度', 'image,compress,jpg,png', 1, 10),
('image-resize', '图片缩放', '图片处理', '批量调整图片尺寸', 'image,resize', 1, 10),
('image-crop', '图片裁剪', '图片处理', '按比例裁剪图片区域', 'image,crop', 1, 10),
('image-format-convert', '图片格式转换', '图片处理', 'JPG/PNG/WebP 等格式互转', 'image,format,convert', 1, 10),
('image-to-icon', '图片转图标', '图片处理', '生成 PNG / ICO / SVG 图标', 'image,icon,svg,ico', 1, 10),
('video-compress', '视频压缩', '音视频', '压缩视频体积，降低码率', 'video,compress,mp4', 1, 10),
('audio-converter', '音频转换', '音视频', 'MP3/WAV/FLAC 格式转换', 'audio,convert,mp3,wav', 1, 10),
('video-to-gif', '视频转 GIF', '音视频', '截取视频片段并导出 GIF', 'video,gif,convert', 1, 10),
('audio-extract', '视频提取音频', '音视频', '从视频中提取音频轨道', 'video,audio,extract', 1, 10),
('video-to-mp3', '视频转 MP3', '音视频', '将视频音轨快速导出为 MP3', 'video,mp3,convert', 1, 10),
('csv-to-json', 'CSV 转 JSON', '数据处理', '将表格 CSV 数据转换为 JSON', 'csv,json,convert', 1, 10),
('json-to-csv', 'JSON 转 CSV', '数据处理', '将 JSON 数据导出为 CSV 表格', 'json,csv,convert', 1, 10),
('sql-formatter', 'SQL 格式化', '数据处理', '格式化 SQL 语句并高亮关键字', 'sql,format', 1, 10),
('standard-line-chart', '在线制作标准折线图', '图表', '输入数据生成标准折线图并导出 PNG', 'chart,line,折线图', 1, 10),
('standard-pie-chart', '在线制作标准饼图', '图表', '输入比例数据生成饼图并支持导出', 'chart,pie,饼图', 1, 10),
('tree-chart', '在线制作树形图', '图表', '使用 JSON 生成树形结构图', 'chart,tree,树形图', 1, 10),
('standard-bar-chart', '在线制作标准柱状图', '图表', '输入分类数据生成柱状图', 'chart,bar,柱状图', 1, 10),
('sankey-chart', '在线制作桑基图', '图表', '通过节点与流向数据生成桑基图', 'chart,sankey,桑基图', 1, 10),
('radar-chart', '在线制作雷达图', '图表', '基于多指标数据生成雷达图', 'chart,radar,雷达图', 1, 10),
('sunburst-chart', '在线制作旭日图', '图表', '使用层级数据生成旭日图', 'chart,sunburst,旭日图', 1, 10),
('scatter-chart', '在线制作散点图', '图表', '输入 XY 数据生成散点图', 'chart,scatter,散点图', 1, 10),
('rose-chart', '在线制作南丁格尔玫瑰图', '图表', '输入分组数据生成玫瑰图', 'chart,rose,玫瑰图', 1, 10),
('donut-chart', '在线制作环形图', '图表', '输入比例数据生成环形图', 'chart,donut,环形图', 1, 10),
('funnel-chart', '在线制作漏斗图', '图表', '输入阶段数据生成漏斗图', 'chart,funnel,漏斗图', 1, 10),
('gauge-chart', '在线制作仪表盘图', '图表', '设置指标数值生成仪表盘图', 'chart,gauge,仪表盘', 1, 10),
('formula-chart', '在线数学公式绘制图表', '图表', '输入函数表达式生成曲线图', 'chart,formula,function', 1, 10),
('word-cloud-chart', '在线制作词云图', '图表', '输入词语与权重生成词云图', 'chart,wordcloud,词云图', 1, 10),
('relationship-graph', '在线生成人物关系图', '图表', '通过节点与关系数据生成关系图', 'chart,graph,关系图', 1, 10),
('mermaid-editor', '在线 Mermaid 图表编辑器', '图表', '在线编辑 Mermaid 语法并生成图表', 'chart,mermaid,diagram', 1, 10),
('zip-compress', '在线 ZIP 文件压缩', '文件', '将多个文件压缩为 ZIP', 'zip,compress,文件', 1, 10),
('zip-extract', '在线 ZIP 解压', '文件', '解压 ZIP 并输出文件包', 'zip,extract,解压', 1, 10),
('text-split', '在线文本文件拆分', '文件', '按行数或字节拆分文本文件', 'text,split,文本', 1, 10),
('file-stamp', '在线文件盖章', '文件', '为 PDF 添加盖章文字', 'stamp,pdf,文件', 1, 10),
('pdf-page-number', '在线 PDF 添加页码', '文件', '为 PDF 批量添加页码', 'pdf,page,number', 1, 10),
('pdf-edit', '在线 PDF 编辑', '文件', '按页码范围保留页面', 'pdf,edit,pages', 1, 10),
('pdf-encrypt', '在线 PDF 加密', '文件', '为 PDF 设置打开密码', 'pdf,encrypt,password', 1, 10),
('pdf-decrypt', '在线 PDF 解密', '文件', '解除 PDF 打开密码', 'pdf,decrypt,password', 1, 10),
('pdf-sign', '在线 PDF 签名', '文件', '为 PDF 添加签名文字', 'pdf,sign,签名', 1, 10),
('pdf-metadata', '在线修改 PDF 元数据', '文件', '查看或更新 PDF 元数据', 'pdf,metadata,元数据', 1, 10),
('batch-rename', '在线批量文件重命名', '文件', '按规则批量重命名文件', 'rename,batch,文件', 1, 10),
('file-merge', '在线文件合并', '文件', '按顺序合并多个文件', 'merge,文件', 1, 10),
('file-split', '在线文件拆分', '文件', '按大小拆分文件', 'split,文件', 1, 10),
('data-process', '在线数据处理', '文件', '对 CSV 指定列执行统计', 'csv,data,统计', 1, 10),
('subtitle-convert', '在线字幕格式转换', '文件', 'SRT/VTT 字幕互转', 'subtitle,srt,vtt', 1, 10),
('encoding-convert', '在线文件编码检测和转换', '文件', '检测并转换文件编码', 'encoding,convert,文件', 1, 10),
('file-type-detect', '在线文件类型检测', '文件', '识别文件类型与 MIME', 'file,type,detect', 1, 10)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    category = VALUES(category),
    description = VALUES(description),
    keywords = VALUES(keywords);
